# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Science Olympiad Website Template
description: "My Site Description Lorem Ipsum Dolor Sit Amet" #A description that will show up in search results
email: youremail+scioly@example.com #A contact email
baseurl: "/SciOly-Website" # the name of your forked repository. If you renamed it to username.github.io, leave this blank.
url: "https://user.github.io" # the base hostname & protocol for your site
# Build settings
markdown: kramdown
include:
